
(jde-project-file-version
 "1.0")
(jde-set-variables
 '(jde-compile-option-directory
  "/home/mikio/dev/fishcatch/android/build/classes/main")
 '(jde-junit-working-directory
  "/home/mikio/dev/fishcatch/android")
 '(jde-compile-option-source
  '(
   "default"))
 '(jde-compile-option-target
  '(
   "default"))
 '(jde-compile-option-command-line-args
  '(
   "-1.7"))
 '(jde-sourcepath
  '(
   "/home/mikio/dev/fishcatch/android/src/main/resources"
   "/home/mikio/dev/fishcatch/android/src/main/java"
   "/home/mikio/dev/fishcatch/android/src"
   "/home/mikio/dev/fishcatch/android/gen"))
 '(jde-global-classpath
  '(
   "/home/mikio/dev/fishcatch/android/build/classes/main"
   "/home/mikio/dev/fishcatch/android/src/main/resources"
   "/home/mikio/dev/fishcatch/android/src/main/java"
   "/home/mikio/dev/fishcatch/android/src"
   "/home/mikio/dev/fishcatch/android/gen"
   "/home/mikio/dev/fishcatch/core/build/libs/core-1.0.jar"
   "/home/mikio/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx-backend-android/1.0-SNAPSHOT/84bf42cfadeb55a3e369220329a1a035f1642030/gdx-backend-android-1.0-SNAPSHOT.jar"
   "/home/mikio/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.0-SNAPSHOT/e544ea790a29a33485f683895bfa6507d805e91d/gdx-1.0-SNAPSHOT.jar")))
