
(jde-project-file-version
 "1.0")
(jde-set-variables
 '(jde-compile-option-directory
  "/home/mikio/dev/fishcatch/core/build/classes/main")
 '(jde-junit-working-directory
  "/home/mikio/dev/fishcatch/core")
 '(jde-compile-option-source
  '(
   "default"))
 '(jde-compile-option-target
  '(
   "default"))
 '(jde-compile-option-command-line-args
  '(
   "-1.6"))
 '(jde-sourcepath
  '(
   "/home/mikio/dev/fishcatch/core/src/main/resources"
   "/home/mikio/dev/fishcatch/core/src"))
 '(jde-global-classpath
  '(
   "/home/mikio/dev/fishcatch/core/build/classes/main"
   "/home/mikio/dev/fishcatch/core/src/main/resources"
   "/home/mikio/dev/fishcatch/core/src"
   "/home/mikio/.gradle/caches/modules-2/files-2.1/com.badlogicgames.gdx/gdx/1.0-SNAPSHOT/e544ea790a29a33485f683895bfa6507d805e91d/gdx-1.0-SNAPSHOT.jar")))
